// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventType } from "./EventType";

export interface HistoryEvent { title: string, sub_title: string, date: string, event_type: EventType, image_id: string, }